### ISSUE TITLE
Add alkaline phosphatase and GGT (gamma glutamyl-transferase) to default key measures

### ISSUE THREAD

**Issue by jwildfire** [SafetyGraphics/safety-eDISH#79]
## Clinical Feature
Users would see GGT and alkaline phosphatase in the longitudinal visit plot, along with ALT, AST and TB. 

## Details
Originally suggested in [a comment](https://github.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/issues/71#issuecomment-398891110) on #71. We just need to update default settings for `measure_details` to implement. 

Will also probably need to add a bit of error checking so that the chart behaves in a reasonable way if one of the default labs listed in `measure_details` isn't found in the data.

**Comment by JimBuchanan** [comment]
Since we closed #71 can this be closed too?

**Comment by jwildfire** [comment]
Right now the longitudinal plots from #71 only show 3 measures (ALT, ALP and TB) by default. This issue is to update the defaults to include Alk Phos and GGT. 

Note that the user could use custom settings to do this (and to add any other measures), so I'd lean towards leaving this until after V1.

**Comment by JimBuchanan** [comment]
Jeremy,

That’s fine. We have the all phos toggle anyway.

Thanks

Jim

Sent from my iPhone

On Jul 16, 2018, at 10:01 PM, jwildfire <notifications@github.com<mailto:notifications@github.com>> wrote:


Right now the longitudinal plots from #71<https://github.com/ASA-DIA-InteractiveSafetyGraphics/safety-eDISH/issues/71> only show 3 measures (ALT, ALP and TB) by default. This issue is to update the defaults to include Alk Phos and GGT.

Note that the user could use custom settings to do this (and to add any other measures), so I'd lean towards leaving this until after V1.
